version: '3'
services:
  app:
    build: .
    ports:
      - "9090:8080"  # Tomcat expone el puerto 8080 por defecto, mapea el puerto 8080 del contenedor al 9090 en el host
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://db:1433;databaseName=yourdatabase
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ComplexPass123!
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: ComplexPass123!
      ACCEPT_EULA: "Y"
      MSSQL_DATABASE: yourdatabase
    ports:
      - "1433:1433"
